application: spbau-notifier-583
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Skip files with filename in these RegEx.
# As recommended in GAE documentation.
skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: view.handler
  secure: always
